#pragma once

enum SpriteRef {
    SPRITE_NUMBER_0 = 0,
    SPRITE_NUMBER_1 = 1,
    SPRITE_NUMBER_2 = 2,
    SPRITE_NUMBER_3 = 3,
    SPRITE_NUMBER_4 = 4,
    SPRITE_NUMBER_5 = 5,
    SPRITE_NUMBER_6 = 6,
    SPRITE_NUMBER_7 = 7,
    SPRITE_NUMBER_8 = 8,
    SPRITE_NUMBER_9 = 9,
    SPRITE_PACMAN_TO_LEFT_OPEN = 100,
    SPRITE_PACMAN_TO_LEFT_CLOSED = 101,
    SPRITE_PACMAN_TO_RIGHT_OPEN = 110,
    SPRITE_PACMAN_TO_RIGHT_CLOSED = 111,
    SPRITE_PACMAN_TO_UP_OPEN = 120,
    SPRITE_PACMAN_TO_UP_CLOSED = 121,
    SPRITE_PACMAN_TO_DOWN_OPEN = 130,
    SPRITE_PACMAN_TO_DOWN_CLOSED = 131,
    SPRITE_PACMAN_IMMOBILE = 140,
    SPRITE_WALL_THICK_HORIZONTAL,
    SPRITE_WALL_THICK_VERTICAL,
    SPRITE_WALL_THICK_BOTTOM_LEFT,
    SPRITE_WALL_THICK_BOTTOM_RIGHT,
    SPRITE_WALL_THICK_TOP_LEFT,
    SPRITE_WALL_THICK_TOP_RIGHT
};
